### ISSUE TITLE
Fix Settings Bugs

### ISSUE THREAD

**Issue by coretechsystems** [coretechsystems/AptOS-G900A#11]
Bugs include, but may not be limited to:
Data Usage - A fault in the GetView syntax of the DataUsageAdapter is causing the Settings app to fully crash when an attempt is made to view the Data Usage graph/toggles.
Volume - The icons in the Volume menu are malformed, and an unknown bug is causing the volume toggles to misbehave, and not modify volumes and/or show current levels.
Battery - An unknown fault in the Fuelgauge part of the Settings app is causing the battery graph to crash when an attempt is made to start it. This issue was supposed to be fixed in the past, but has resurfaced in newer builds, including the Final Release build.
Storage - An issue (most likely malformed code) is causing the Storage section to display incorrect labels and a repeating "USB Storage" option section.

Solutions:
1. Full decompilation of the settings APK down to Java using JADX, and then a fix and rebuild.
|>This hasn't worked so far since the required dependencies are missing, and Android Studio subsequently fails to build.
2. Attempt to fix the issues by "splicing" elements from the TouchWiz settings APK to try and fix the issue.
|>Attempts have been made to use this option, but have produced very little results.

**Comment by AptLogic** [comment]
A possible fix for the issue may be changing the settings.jar file present in /system/framework/settings.jar
It is possible that this is a root cause of the issues.

**Comment by AptLogic** [comment]
^^ Nope, problem is still present.

**Comment by AptLogic** [comment]
Bug moved to Kalmia for additional fix research

**Comment by AptLogic** [comment]
The storage bug has been fixed through some fixes in the framework-res.apk file.
The battery bug (should) be fixed now through that same process, but this fix is awaiting confirmation.

**Comment by ghost** [comment]
The battery section still crashes when attempting to load it. The storage fix is working.

**Comment by AptLogic** [comment]
The storage fix works because that bug was caused by something in the
framework-res file. It was an incorrectly set value leading the system to
think multiple USB storage slots were necessary.
By comparison, this issue seems to be a problem with the listview adapter
either in the settings apk itself or in the system as a whole, but I
haven't been able to pin down exactly where the issue is.

**Comment by ghost** [comment]
Got it. Is listview responsible for the Accessibility crashes too?

**Comment by AptLogic** [comment]
Partially.
They're both part of the android.widget library, but the accessibility
issue is caused by the settings app calling the ImageView adapter on "a
null object reference", which can either mean the core ImageView adapter is
flawed or the settings app is calling it incorrectly.
